# Generated by Django 4.0.4 on 2022-11-29 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='addres',
            new_name='address',
        ),
    ]
