# Generated by Django 4.0.4 on 2022-11-29 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0002_rename_addres_register_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='role',
            new_name='roll',
        ),
    ]
