# Generated by Django 4.0.4 on 2022-12-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0003_rename_role_register_roll'),
    ]

    operations = [
        migrations.CreateModel(
            name='test1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('mobile', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
